apiVersion: v2
name: navlinkswebhook
description: A Helm chart for Admission Webhook to create Navlinks for Prometheus
type: application
version: 2.1.1-rc0
appVersion: "2.1.0"
maintainers:
- name: eumel8
  email: f.kloeker@telekom.de
  url: https://www.telekom.com
